### PR TITLE
Added an option for the amount of partitions

### PR DESCRIPTION
**Pull request by RichardLitt**
This may be helpful. Was for me.

### CODE REVIEW

**Comment by m59peacemaker** [comment]
@RichardLitt  I'll check it out when I get a chance! Thanks!

**Comment by m59peacemaker** [comment]
@RichardLitt  Sorry I'm just getting around to this. I feel that it would make more sense to use a different filter to influence the amount of items like `limitTo: 6 | partition: 3` for 2 partitions. Is there a case where the partition filter does need to be responsible for this?

**Comment by RichardLitt** [comment]
That may also work, I hadn't thought of that. This makes it so that you can only have a multiple of the partition size, unlike limitTo which could be 7 for a partition of 3. That may be an added benefit.

**Comment by m59peacemaker** [comment]
I'm not sure which one you're saying is more beneficial. I find `limitTo` to make the most since because it can accomplish the same goal here, but allows more flexibility. I feel pretty confident it would be breaking the SRP to add functionality like that to this filter.

**Comment by RichardLitt** [comment]
I wasn't stating which one was more beneficial; I don't know. I think you're right that `limitTo` is probably a better option.

**Pull request closed without merging**
